### ISSUE TITLE
Invalid interaction URL:s crash some lists

### ISSUE THREAD

**Issue by voxpelli** [voxpelli/webpage-webmentions#206]
This is the error I'm getting in the backend:

```
Error: Invalid URL, should be an absolute one (tag:indieweb.social:112331285963196700/,2013)
  at normalizeUrlRaw (/app/lib/utils/url-tools.js:28:11)
  at normalizeUrl (/app/lib/utils/url-tools.js:53:58)
  at /app/lib/classes/entries.js:88:36
  at Array.map (<anonymous>)
  at Entries._resolveDerivedData (/app/lib/classes/entries.js:88:25)
  at Entries._distillMention (/app/lib/classes/entries.js:117:15)
  at /app/lib/classes/entries.js:301:26
  at Array.map (<anonymous>)
  at /app/lib/classes/entries.js:301:10
```

Temporary solution is to run ~~one of the queries (https://github.com/voxpelli/webpage-webmentions/issues/208#issuecomment-2429253424 or https://github.com/voxpelli/webpage-webmentions/issues/208#issuecomment-2165109424) and edit out the interactions from `entries.data` manually~~ this query:

```sql
UPDATE
  entries
SET
  data = regexp_replace(entries.data::varchar, ',?"tag:[^"]+"', '', 'g')::json
WHERE
  jsonb_path_exists(to_jsonb(entries.data), '$.interactions[*] ? (@ like_regex "^tag:")') = true
```

If there's a `\u0000` error, then do this and edit them manually:

```sql
SELECT entries.id
FROM entries
INNER JOIN mentions ON mentions.eid = entries.id
WHERE
  entries::TEXT LIKE '%\u0000%'; 
ORDER BY fetched DESC
LIMIT 100
```

_Originally posted by @voxpelli in https://github.com/voxpelli/webpage-webmentions/issues/205#issuecomment-2098158868_

**Comment by voxpelli** [comment]
Still happening: https://github.com/voxpelli/webpage-webmentions/issues/208#issuecomment-2429253424
